version: '3.8'

services:
  php:
    container_name: php81-sf6
    build: ./php81-sf6
    volumes:
      - ./project:/var/www/html
    environment:
      TZ: Europe/Paris
    depends_on:
      - database
      - mailer

  web:
    image: nginx:alpine
    container_name: nginx-sf6
    ports:
      - "9000:80"
    volumes:
      - ./project:/var/www/html
      - ./php81-sf6/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  database:
    image: postgres:13-alpine
    container_name: symfony6-db
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: ChangeMe
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: symfony6-adminer
    ports:
      - "8080:8080"
    depends_on:
      - database

  pgadmin:
    image: dpage/pgadmin4
    container_name: symfony6-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - database

  mailer:
    image: schickling/mailcatcher
    container_name: symfony6-mailer
    ports:
      - "1025:1025"
      - "1080:1080"

volumes:
  db-data:
